### ISSUE TITLE
what's difference between  CoI Agent and gpt-researcher

### ISSUE THREAD

**Issue by CoderYiFei** [DAMO-NLP-SG/CoI-Agent#1]
gpt-researcher:
https://github.com/assafelovic/gpt-researcher

**Comment by jianghuyihei** [comment]
> CoderYiFei

Essentially, we've introduced the "chain-of-ideas" structure to help LLMs think more effectively. This is akin to telling an LLM 1, 2, 3, and then asking what the next number is. On the other hand, GPTResearcher resembles traditional RAG methods, where the LLM is given 1, 4, 12, 11 and asked to predict the next number. While there might be some patterns, they are not as straightforward as 1, 2, 3. I hope this explanation makes sense to you. For more details, you can refer to our paper: https://arxiv.org/pdf/2410.13185. In our evaluation process, we also used GPTResearcher as our baseline.
