### ISSUE TITLE
Would all the generated ideas be released in future?

### ISSUE THREAD

**Issue by tarun360** [DAMO-NLP-SG/CoI-Agent#11]
Hello,

One generated idea is mentioned in Table 3. Would all the other generated ideas be also released sometime in future?

**Comment by jianghuyihei** [comment]
> Hello,
> 
> One generated idea is mentioned in Table 3. Would all the other generated ideas be also released sometime in future?
If you're interested, we can provide you with the ideas we've generated. Of course, creating ideas is straightforward; you can use our code to generate them directly.

**Comment by jianghuyihei** [comment]
> If you could share the generated ideas which were used in the paper (human study) that would be very helpful @jianghuyihei

We have newly provided the case in the GitHub repository, located at path case/case.json.

**Comment by jianghuyihei** [comment]
> > We have newly provided the case in the GitHub repository, located at path case/case.json
> 
> @jianghuyihei that only includes 1 generated idea (EvoResearchAgent).
> 
> Can all the ideas generated by CoI agent be shared?

I have uploaded the experimental results to case/all_case.json. May I know your specific purpose for using it, if possible? If our method has inspired you, please be sure to let us know. Thank you very much.
