### ISSUE TITLE
Failed to generate idea

### ISSUE THREAD

**Issue by sky-fly97** [DAMO-NLP-SG/CoI-Agent#6]
Hi, I seem to be stuck between searching papers and regenerating query, it will keep looping and eventually fail to generate, but I see that there are papers in the 'deep_papers' folder.
```
<query>3D object classification point cloud</query>
Failed to search papers for Deep learning techniques for point cloud shape classification, regenerating query 3D object classification point cloud to search papers.
failed to generate idea 3d shape classification from point cloud
begin to generate experiment
```
In 'review_experiment_suggestions.json', "idea" is null.

**Comment by JohannaYe** [comment]
same issue

**Comment by jianghuyihei** [comment]
> Hi, I seem to be stuck between searching papers and regenerating query, it will keep looping and eventually fail to generate, but I see that there are papers in the 'deep_papers' folder.
> 
> ```
> <query>3D object classification point cloud</query>
> Failed to search papers for Deep learning techniques for point cloud shape classification, regenerating query 3D object classification point cloud to search papers.
> failed to generate idea 3d shape classification from point cloud
> begin to generate experiment
> ```
> 
> In 'review_experiment_suggestions.json', "idea" is null.

This is because no relevant papers were retrieved based on this topic (my code logic is to constantly rewrite the query for retrieval until a fixed number of times is reached), you can try to simplify your topic.
