### ISSUE TITLE
Failed to use online demo

### ISSUE THREAD

**Issue by hajkeoadf** [DAMO-NLP-SG/CoI-Agent#9]
When I tried to generate, came the error:
```
Error
unsupported operand type(s) for *: 'NoneType' and 'NoneType'
```

**Comment by jianghuyihei** [comment]
> When I tried to generate, came the error:
> 
> ```
> Error
> unsupported operand type(s) for *: 'NoneType' and 'NoneType'
> ```

Can you provide more specific error location? This issue may occur in several places, such as your OpenAI embedding API not being filled in correctly

**Comment by jianghuyihei** [comment]
> When I tried to generate, came the error:
> 
> ```
> Error
> unsupported operand type(s) for *: 'NoneType' and 'NoneType'
> ```

I understand what you mean. This is due to our API replacement, and I will make the necessary corrections immediately
